name: Laravel on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] jobs:
  create_deployment_artifacts:
    name: Create deploymnet artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure PHP 7.4
      use: shivammathur/setup-php@master
      with:
          php-version: 7.4
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml, zip
     
     
    - name: Composer install
     run: |
     composer install --no-dev --no-interaction --prefer-dist
